language: python

python:
  - "3.6"

# Add separate test environments for the docs and flake8 linter.

jobs:
  include:
    - name: "Docs"
      install:
        - pip install -r requirements.txt
        - python setup.py install
      script: python -m sphinx.cmd.build -E -W -v -T doc/source doc/build
    - name: "Lint"
      install: pip install flake8
      script: flake8 -v sphinxcontrib setup.py

